HEADERS += src/domain/UBGraphicsScene.h \
    src/domain/UBGraphicsItemUndoCommand.h \
    src/domain/UBGraphicsTextItemUndoCommand.h \
    src/domain/UBGraphicsItemTransformUndoCommand.h \
    src/domain/UBGraphicsPixmapItem.h \
    src/domain/UBPageSizeUndoCommand.h \
    src/domain/UBGraphicsProxyWidget.h \
    src/domain/UBGraphicsSvgItem.h \
    src/domain/UBGraphicsPolygonItem.h \
    src/domain/UBItem.h \
    src/domain/UBGraphicsWidgetItem.h \
    src/domain/UBGraphicsPDFItem.h \
    src/domain/UBGraphicsTextItem.h \
    src/domain/UBResizableGraphicsItem.h \
    src/domain/UBGraphicsStroke.h \
    src/domain/UBGraphicsMediaItem.h \
    src/domain/UBGraphicsGroupContainerItem.h \
    src/domain/UBGraphicsGroupContainerItemDelegate.h \
    src/domain/UBGraphicsStrokesGroup.h \
    src/domain/UBGraphicsItemGroupUndoCommand.h \
    src/domain/UBGraphicsItemDelegate.h \
    src/domain/UBGraphicsTextItemDelegate.h \
    src/domain/UBGraphicsDelegateFrame.h \
    src/domain/UBGraphicsWidgetItemDelegate.h \
    src/domain/UBGraphicsMediaItemDelegate.h \
    src/domain/UBSelectionFrame.h \
    src/domain/UBUndoCommand.h \
    src/domain/UBGraphicsItemZLevelUndoCommand.h \
    $$PWD/UBShapeFactory.h \
    $$PWD/UB1HEditableGraphicsSquareItem.h \
    $$PWD/UB1HEditableGraphicsCircleItem.h \
    $$PWD/UBGraphicsFreehandItem.h \
    $$PWD/UBEditableGraphicsPolygonItem.h \
    $$PWD/UBEditableGraphicsRegularShapeItem.h \
    $$PWD/UBGraphicsLineItem.h \
    $$PWD/UBGraphicsRectItem.h \
    $$PWD/UBGraphicsEllipseItem.h \
    $$PWD/UBAbstractGraphicsPathItem.h \
    $$PWD/UBAbstractGraphicsItem.h \
    $$PWD/UB3HandlesEditable.h \
    $$PWD/UBShapeEditable.h \
    $$PWD/UBAbstractHandle.h \
    $$PWD/UBEditable.h \
    $$PWD/UBAbstractEditableGraphicsPathItem.h \
    $$PWD/UB1HEditableGraphicsBasicShapeItem.h \
    $$PWD/UBFreeHandle.h \
    $$PWD/UBAbstractHandlesBuilder.h \
    $$PWD/UBHorizontalHandle.h \
    $$PWD/UBVerticalHandle.h \
    $$PWD/UBDiagonalHandle.h \
    $$PWD/UBAlignObjectManager.h \
    $$PWD/UBAbstractGraphicsProxyWidget.h

SOURCES += src/domain/UBGraphicsScene.cpp \
    src/domain/UBGraphicsItemUndoCommand.cpp \
    src/domain/UBGraphicsTextItemUndoCommand.cpp \
    src/domain/UBGraphicsItemTransformUndoCommand.cpp \
    src/domain/UBGraphicsPixmapItem.cpp \
    src/domain/UBPageSizeUndoCommand.cpp \
    src/domain/UBGraphicsProxyWidget.cpp \
    src/domain/UBGraphicsSvgItem.cpp \
    src/domain/UBGraphicsPolygonItem.cpp \
    src/domain/UBItem.cpp \
    src/domain/UBGraphicsWidgetItem.cpp \
    src/domain/UBGraphicsPDFItem.cpp \
    src/domain/UBGraphicsTextItem.cpp \
    src/domain/UBResizableGraphicsItem.cpp \
    src/domain/UBGraphicsStroke.cpp \
    src/domain/UBGraphicsMediaItem.cpp \
    src/domain/UBGraphicsGroupContainerItem.cpp \
    src/domain/UBGraphicsGroupContainerItemDelegate.cpp \
    src/domain/UBGraphicsStrokesGroup.cpp \
    src/domain/UBGraphicsItemGroupUndoCommand.cpp \
    src/domain/UBGraphicsItemDelegate.cpp \
    src/domain/UBGraphicsTextItemDelegate.cpp \
    src/domain/UBGraphicsMediaItemDelegate.cpp \
    src/domain/UBGraphicsDelegateFrame.cpp \
    src/domain/UBGraphicsWidgetItemDelegate.cpp \
    src/domain/UBSelectionFrame.cpp \
    src/domain/UBUndoCommand.cpp \
    src/domain/UBGraphicsItemZLevelUndoCommand.cpp \
    $$PWD/UBShapeFactory.cpp \
    $$PWD/UB1HEditableGraphicsSquareItem.cpp \
    $$PWD/UB1HEditableGraphicsCircleItem.cpp \
    $$PWD/UBGraphicsFreehandItem.cpp \
    $$PWD/UBEditableGraphicsPolygonItem.cpp \
    $$PWD/UBEditableGraphicsRegularShapeItem.cpp \
    $$PWD/UBGraphicsLineItem.cpp \
    $$PWD/UBGraphicsRectItem.cpp \
    $$PWD/UBGraphicsEllipseItem.cpp \
    $$PWD/UBAbstractGraphicsPathItem.cpp \
    $$PWD/UBAbstractGraphicsItem.cpp \
    $$PWD/UB3HandlesEditable.cpp \
    $$PWD/UBShapeEditable.cpp \
    $$PWD/UBAbstractHandle.cpp \
    $$PWD/UBEditable.cpp \
    $$PWD/UBAbstractEditableGraphicsPathItem.cpp \
    $$PWD/UB1HEditableGraphicsBasicShapeItem.cpp \
    $$PWD/UBFreeHandle.cpp \
    $$PWD/UBAbstractHandlesBuilder.cpp \
    $$PWD/UBHorizontalHandle.cpp \
    $$PWD/UBVerticalHandle.cpp \
    $$PWD/UBDiagonalHandle.cpp \
    $$PWD/UBAlignObjectManager.cpp \
    $$PWD/UBAbstractGraphicsProxyWidget.cpp
