#ifndef UBCFFADAPTOR_GLOBAL_H
#define UBCFFADAPTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UBCFFADAPTOR_LIBRARY)
#  define UBCFFADAPTORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UBCFFADAPTORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UBCFFADAPTOR_GLOBAL_H
