#
# Version
#

set(VERSION "${${PROJECT_NAME}_VERSION}-${VERSION_TYPE}.${VERSION_BUILD}")

if(VERSION_TYPE STREQUAL "r")
    set(VERSION "${${PROJECT_NAME}_VERSION}")
endif()

if(WIN32)
    set(VERSION_RC "${${PROJECT_NAME}_VERSION_MAJOR},${${PROJECT_NAME}_VERSION_MINOR},${${PROJECT_NAME}_VERSION_PATCH},${VERSION_TYPE},${VERSION_BUILD}")
else()
    set(VERSION_RC "${${PROJECT_NAME}_VERSION_MAJOR},${${PROJECT_NAME}_VERSION_MINOR},${${PROJECT_NAME}_VERSION_PATCH},${VERSION_TYPE}")
endif()

string(REPLACE "a" "160" VERSION_RC ${VERSION_RC}) # 0xA0
string(REPLACE "b" "176" VERSION_RC ${VERSION_RC}) # 0xB0
string(REPLACE "rc" "192" VERSION_RC ${VERSION_RC}) # 0xC0
string(REPLACE "r" "240" VERSION_RC ${VERSION_RC}) # 0xF0 

add_compile_definitions(UBVERSION="${VERSION}")
add_compile_definitions(UBVERSION_RC=${VERSION_RC})
